### ISSUE TITLE
Use semver (and PHPStan version constraints in composer.json)

### ISSUE THREAD

**Issue by agnyp** [spaze/phpstan-disallowed-calls#25] opened 2020-09-03 09:23 UTC
Hello,

firstly, thanks for the very userful plugin.

I'd habe a suggestion though. Could you please use versioning-numbers as they are ([usually](https://semver.org/)) intended? If you have breaking changes you should increase the major number, or at least the minor, for that matter.
We use the plugin in our pipeline and am quite busy fixing it over the last weeks.^^
With proper numbering I could use composer to update only minor (non-breaking) changes / patches, and deal with the big one on my machine first.

**Comment by spaze** [comment] 2020-09-03 09:47
Hey, thanks for the issue, happy you find it useful!

I've decided to follow PHPStan's versioning. When PHPStan is 0.12.x, this extension is 0.12.x too. The release that has worked with 0.11 stopped working with PHPStan 0.12, and that was when I've decided to follow the numbering.

I'm sorry you had to spend some time fixing your pipeline. I try to provide all upgrade instructions in https://github.com/spaze/phpstan-disallowed-calls/releases and sorry if I had missed something. The only breaking change I remember introducing is [the requirement of `DisallowedHelper`](https://github.com/spaze/phpstan-disallowed-calls/tree/v0.12.2), it would help if you can share what you had to fix so I can better understand and avoid it in the future or provide clear instructions or backwards compatibility (having said that, this should have been a proper extension with installer support since day one but here we are).

I'm not sure closely following semver is possible. When PHPStan releases 0.13 and this extension needs to be updated to use the new internals but doesn't introduce any breaking changes, what version should that be? I'm open to ideas how to indicate this version is for PHPStan 0.12 and still somehow mark breaking changes. I'm not sure 0.12.x.y (instead of just 0.12.x) would be fine but seems like the best option at the moment. Let me know hat you think.

Again, sorry, and thanks!

**Comment by agnyp** [comment] 2020-09-03 12:08
I understand. Let me first tell you the problems we encountered:
First, as you mentioned, the requirement of DisallowedHelper. Lastly, your lib insisted on naming at least one method in one of the rules (\Disallowed\MethodCalls). I left it empty for other developers as a template. I removed it for now, until I update to phpstan/extension-installer.

Both was an easy fix, but broke the pipe upfront, unfortunately.

I found your releases-page, in search for the versions ;-), which is very well documented, btw. 👍
So, of course, if I had had a look ... and for the time being, I can live with looking up your pages and updating your plugin/phpstan regularly by hand.

For the versioning: I see your point there, and I'd have a suggestion/idea.
I believe people are used to versions differ from main-app and respective plugins. Though, I've never built a plugin for php or phpstan before, I believe it should be possible to tie your version to a specific version of phpstan. Composer should have this capability and you could document additionally in your releases-doc, which versions fit.

This way, composer (or another function) would make certain the versions match, and you'd be free to use semver independently of phpstan. You could start with 1.0.0, since I believe your tool is production-ready. 😉

**Comment by spaze** [comment] 2020-09-03 12:35
Thanks for the info, and again sorry for the trouble caused, definitely not intended :)

However, I don't understand this:

> Lastly, your lib insisted on naming at least one method in one of the rules (\Disallowed\MethodCalls).

Do you mean that you have to disallow at least one method? That's definitely not something I'm aware of and not something I can reproduce.

Can you share your config that has caused issues? Feel free to email me, if you don't want to share it publicly. Maybe I have an idea what went wrong but would like to be sure. (If you're not using `extension.json` you'd still need to define `disallowedMethodCalls` in your config, even if empty `disallowedMethodCalls: []`, which is something I haven't realized until now, eh - is this the issue you've hit?)

I don't plan any significant updates to this extension in the near future so you should be fine for the next few weeks at least :-) The last 4 or so releases should have also been rolled into one version. And you're totally right about composer and version constraints, totally forgot about that, thanks! 👍

I'll keep this issue open and will think about version numbers/semver when releasing next version. I don't agree with this being production-ready :-) but thank you!

**Comment by agnyp** [comment] 2020-09-03 13:09
No worries ... the problems were quickly fixed. ;-)

I got this:

```
$ phpstan analyse -c .phpstan.neon
In DisallowedHelper.php line 84:
                                                                    
  Either 'method' or 'function' must be set in configuration items  
```
then I removed this:
```
  - class: Spaze\PHPStan\Rules\Disallowed\MethodCalls
    tags:
      - phpstan.rules.rule
    arguments:
      forbiddenCalls:
        - method: ''
          message: ''
```
and everything was happy again. 

Alright, I'll feel relaxed for the next few weeks and thank you very much for the quick and great response(s)!

I'll be watching and am curious how you'll decide with the versioning. ;-)

... if you need more input regarding the issues, or anything, shoot.

**Comment by spaze** [comment] 2020-09-03 14:43
Aha! I see the problem, thanks for the config snippet. Empty `method` or `function` (`method: ''`) is now not supported (it was supported unintentionally). You can still just comment those out if you'd like to preserve a template.

Enjoy your next few weeks and thanks! :-)

**Comment by spaze** [comment] 2020-09-03 16:30
Oh, just remembered, the new version contains a prepackaged config file called `disallowed-dangerous-calls.neon` with some of the *World's Most Dangerous Functions™*, you can also reference that file as a template in your comment (and you can even include it in your config if you feel like).

**Comment by spaze** [comment] 2020-10-19 02:57
In the past few weeks I've done some reliability changes, meaning more things are now detected. I stayed on 0.12.x because they were not breaking changes but rather fixing what probably everyone would expect was detected.

To detect `eval()` and constructor calls, new internal services had to be introduced so I've bumped to 1.0.0. I still plan to write release notes that should help people upgrade (I very much like that myself). I think I can safely close this issue, I can now semver easily once the PHPStan version "pairing" is gone.

**Closed by spaze** 2020-10-19 02:57 UTC
